{ pkgs }:

[ 
    pkgs.fastfetch
    pkgs.vscode
    pkgs.firefox-wayland
    pkgs.swww
    pkgs.grim
    pkgs.slurp
    pkgs.openvpn
    pkgs.scribus
    pkgs.rofi-wayland
    pkgs.swaynotificationcenter
    pkgs.wlr-randr
    pkgs.ydotool
    pkgs.wl-clipboard
    pkgs.hyprland-protocols
    pkgs.hyprpicker
    pkgs.swayidle
    pkgs.swaylock
    pkgs.xdg-desktop-portal-hyprland
    pkgs.hyprpaper
    pkgs.xdg-utils
    pkgs.qt5.qtwayland
    pkgs.qt6.qmake
    pkgs.qt6.qtwayland
    pkgs.adwaita-qt
    pkgs.adwaita-qt6
    pkgs.hyprland
    pkgs.lxqt.lxqt-policykit
    pkgs.xfce.thunar
    pkgs.bottles
]